## Basic Configuration

baseurl = "https://gullofash.com"
builddrafts = false
canonifyurls = true
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Changyang Tseng"
title = "Changyang Tseng-曾畅扬的博客"

theme = "hugo-goa"

## Hugo Built-in Features
disqusShortname = "gullofash-com" # Comment out to disable Disqus.
googleAnalytics = "UA-130437660-1"
enableRobotsTXT = true

## Site Settings
[params]
author = "Changyang Zeng"
intro = "Senior student majoring in geotechnical engineering"
description = "Free coding.<br/> \"Rise above. Focus on science.\""
authorimage = "me.jpg"
dateformat = "Dec 2, 2018"

## Site Meta Settings
[params.meta]
description = "Simple minimalist theme"
keywords = "minimalist,blog,goa,hugo,developer"

## Social Accounts
[params.social]
github = "Heceo"
instagram = "<changyangzeng>"
#xing = "<username>"
linkedin = "畅扬-曾-169a47133"
twitter = "Fowles7440163"
facebook = "GroundControltoMajorZeng"
google = "<username>"
#stackoverflow = "<username>"
#lastfm = "<username>"
#goodreads = "<username>"
#gitlab = "<username>"
#bitbucket = "<username>"
#fivehundredpx = "<username>"
#flickr = "<username>"
#foursquare = "<username>"
hackernews = "<username>"
#kickstarter = "<username>"
#patreon = "<username>"
pintrest = "<username>"
steam = "<username>"
reddit = "<username>"
snapchat = "<username>"
youtube = "<username>"
#keybase = "<username>"
#twitch = "<username>"
#soundcloud = "<username>"
tumblr = "<username>"
skype = "<username>"
telegram = "Heceo"
whatsapp = "<username>"
email = "gullofash@gmail.com"

## Extras
[params.extra]
copyright = "© 2018. Ch'angyang Tseng. [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/)."
poweredby = true
highlightjs = true
socialmarkup = true

## Main Menu
[[menu.main]]
    name = "blog"
    weight = 100
    identifier = "blog"
    url = "/blog/"
[[menu.main]]
    name = "about"
    identifier = "about"
    weight = 200
    url = "/about/"
[[menu.main]]
    name = "coderag"
    identifier = "coderag"
    weight = 300
    url = "/coderag/"
